#!/usr/bin/python3

import sys
import gpiozero as gpio
from gpiozero import LED
from time import sleep
import math

relay = LED("GPIO18",initial_value=True)
duration = int(43200)

def lights_on():
    try:
        print("Christmas lights: ON")
        relay.on()
        sleep(duration)
    except:
        KeyboardInterrupt

def lights_off():
    print("Christmas lights: OFF")
    relay.off()

if __name__ == '__main__':
    status = sys.argv[1]

    if status == "on":
        lights_on()

    if status == "off":
        lights_off()

else:
    print('loading as library')

